---
title: "DMA"
output: html_document
date: "2022-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library("odbc")
library("RODBC")
library("DBI")
library("dplyr")
library(ggplot2)
library(sqldf)
library(usmap)
library(maptools)
library(rgdal)
library(tidygeocoder)
library('ggmap')
```

```{r}

con <- dbConnect(odbc::odbc(), .connection_string = "Driver={MySQL ODBC 8.0 Unicode Driver};", server="localhost", Database = "rental_management_system", UID = "root", PWD = 'Srinivas@1', Port = 3306)


```



```{sql connection=con, output.var = "mydataframe"}

#1 FIND THE REVENUE GENERATED BY THE RENTAL MANAGEMNET FIRM FROM EACH PAYMENT TYPE ( ASSUMING 15% OF TOTAL AMOUNT TRANSFERRED BY EACH TYPE IS THE REVENUE FOR RENTAL MANAGENT FIRM)

   WITH REVENUE AS 
             (SELECT PAYMENT_TYPE, AMOUNT_TRANSFERRED 
              FROM PAYMENT)
                         SELECT PAYMENT_TYPE, SUM(AMOUNT_TRANSFERRED)*0.15 AS REVENUE_GENERATED 
                         FROM REVENUE 
                         GROUP BY PAYMENT_TYPE;
                         

```

```{r}


ggplot(mydataframe, aes(x=PAYMENT_TYPE, y= REVENUE_GENERATED))+ geom_bar(stat="identity", fill="steelblue")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ggtitle("REVENUE GENERATED FROM EACH PAYMENT TYPE")



```


```{sql connection=con, output.var = "department"}

#2 Find the percentage of technicians in each department.

SELECT DEPARTMENT, COUNT(*) AS NUMBER FROM TECHNICIAN GROUP BY DEPARTMENT;


``` 

```{r}

department$NUMBER <- as.integer(department$NUMBER)
df <- department %>% 
  group_by(NUMBER) %>%
  ungroup() %>% 
  mutate(perc = `NUMBER` / sum(`NUMBER`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(df, aes(x="", y= NUMBER , fill=DEPARTMENT)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +  geom_text(aes(label = labels), position = position_stack(vjust=0.5)) +
  labs(x = NULL, y = NULL) +
  theme_classic() +
  theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank()) +
  scale_fill_brewer(palette="Blues")  + ggtitle("PERCENTAGE OF TECHNICIANS IN EACH DEPARTMENT")



``` 



```{sql connection=con, output.var = "time"}

# Find number of maintenance requests in particular time of the day

SELECT DATE_FORMAT(REQUEST_TIME, '%H') AS TIME, count(*) AS NUMBER FROM MAINTENANCE_REQUEST GROUP BY TIME ORDER BY TIME ;



```


```{r}

time$NUMBER <- as.integer(time$NUMBER)

ggplot(time, aes(x = TIME, y = NUMBER,group=1)) + geom_line() + geom_point()  + ggtitle("NUMBER OF MAINTENANCE REQUESTS IN PARTICULAR TIME OF THE DAY")

```